### ISSUE TITLE
what's the type of function start parameter payload?

### ISSUE THREAD

**Issue by pangbingqiang** [Wizcorp/marathon-client.py#2]
Hi, when i use the api interface,i face a problem.in the start fucntion ,what's kind of the input parameter paylod? thanks

**Comment by MiLk** [comment]
Hello,

The payload is the one documented here: https://mesosphere.github.io/marathon/docs/rest-api.html#post-/v2/apps

**Comment by pangbingqiang** [comment]
thanks~~ i use it successful. i got another problem:how can l know my app run in which mesos slave machine? i use marathon.endpoints() function, it return the value like this:
                              hello 10962   localhost:31107

**Comment by MiLk** [comment]
The `localhost` should be the hostname/ip of the slave.

**Comment by pangbingqiang** [comment]
Hi Milk,I use the api creat a app to run my own python script.my script is in my server,my code is :
marathon.start({"id":"rm","cmd":"./RM.py","cpus":1.0,"mem":32.0,"disk":0.0,"instances":1, "uris": ["https://localhost/RM.py"]})
I find it don't work,so how can I run my python script by api interface,thanks~~

**Comment by MiLk** [comment]
How many slaves do you have?
If you launch more than 1 task, what's the ouput of `marathon.endpoints()` ?

**Comment by pangbingqiang** [comment]
I have tow slave.my script just call the external program,and I have run it alone ,its ok.
the  marathon.endpoints()  return like this:
 rm 19742   distribute1:31204  
but the problem is the return slave node ip:port(distribute1:31204) is always change,i dont konw why?

**Comment by MiLk** [comment]
Marathon allocates resources where there are free resources.
Each time you start your app, it will run on a different slave/port.
That's why you have to use the endpoints command to know where it's running.

Here you app is running on the slave distribute1 on the port 31204.

You can install https://github.com/Wizcorp/frontrunner to set up a proxy which will use the same port for your application and automatically proxy the requests to the right backend.
You will have to specify a value for the `ports` parameter in your payload for the start method.

**Comment by pangbingqiang** [comment]
if i run tow tasks,the  marathon.endpoints()  return like this:
  rm    11638   distribute1:31027   distribute-3:31849  
also the slave node ip:port is always change, i guess the  "uris[]"  input maybe wrong, but i dont konw the value it is? my python script is in my linux server

**Comment by MiLk** [comment]
It's ok, your application is running on:
- distribute1:31027
- distribute-3:31849

I don't really see what's your problem.
You can't fix the port used by the app on the slaves.

**Comment by pangbingqiang** [comment]
thanks ,maybe i describe it not clearly.when app is running, marathon.endpoints() return value slave node ip:port always change .

**Comment by MiLk** [comment]
Did you check the status of your app in the mesos web ui?
Maybe your app is crashing or restarting.

**Comment by pangbingqiang** [comment]
i check the mesos  web  ui, task status is staging  then  failed.but i have run the script alone it work right

**Comment by MiLk** [comment]
Via the mesos UI you can have access to the sandbox of the failed tasks and you have access to the error logs.

**Comment by pangbingqiang** [comment]
i view the slave log, the error is:
failed to start: Failed to fetch URIs for container 'e4dc6434-56a9-4ac6-85e5-075ea3726893': exit status 256
its really the uris input parameter is error. my script is in my linux server,so how can i set  this value?

**Comment by MiLk** [comment]
What do you set as uris?
Here we're using Amazon S3 to store our archives.
But you can do whatever you want as long your server is able to dowload the archive.

**Comment by pangbingqiang** [comment]
my uris is:
“uris”: [ http://myserver ip/RM.zip]
myserver have install apache server,and i can use firefox to download by input http://myserver ip/RM.zip

**Comment by MiLk** [comment]
Can your mesos server access this url? Try with `curl` or `wget`.

**Comment by pangbingqiang** [comment]
hi Milk,when i use marathon i found a problem,my json file is:
{
  "id": "helloworld",
  "cmd": "./Hello/hello -Dhttp.port=$PORT",
  "mem": 512,
  "cpus": 1.0,
  "instances": 1,
  "uris": [
    "http://10.175.100.231/Hello.zip"
  ]
}
hello is a exe file just printf hello world,i find it cannot work,task failed then restart soon,error log is:
E1022 16:40:13.883605 15124 slave.cpp:2484] Container 'bc31a168-663d-47f8-9a62-4588f836f8a3' for executor 'hello.ae37e94f-5a0a-11e4-8b22-283152ac61ed' of framework '20141008-182043-16777343-5050-8143-0000' failed to start: Container destroyed during launch
E1022 16:40:13.883955 15122 slave.cpp:2577] Termination of executor 'hello.ae37e94f-5a0a-11e4-8b22-283152ac61ed' of framework '20141008-182043-16777343-5050-8143-0000' failed: Unknown container: bc31a168-663d-47f8-9a62-4588f836f8a3
E1022 16:40:13.884119 15125 slave.cpp:2863] Failed to unmonitor container for executor hello.ae37e94f-5a0a-11e4-8b22-283152ac61ed of framework 20141008-182043-16777343-5050-8143-0000: Not monitored

when i change then "cmd" as :
"cmd": "./Hello/hello -Dhttp.port=$PORT && sleep 10",
it works ,the task can finish,i dont know why?
Also how can i see my task result,how can i konw the running result is right? thanks

**Comment by MiLk** [comment]
In the mesos webui you should be able to access to the log files of your task.
There are two different files for stdout and stderr, you should be able to get more info.
